tubes/models.py
import hashlib
import os
from shutil import copyfile

from flask import url_for

from tubes import db

COLORS = [
    "#b80f2b",
    "#33ae8a",
    "#9a8e00",
    "#b1f01f",
    "#1abffa",
    "#a1958c",
    "#8b95db",
    "#d7757e",
    "#ae2862",
    "#f732e7",
    "#a76fa8",
    "#a753f6",
    "#a8ea28",
    "#e49c6d",
    "#f2c436",
    "#2b5764",
]


class SoundQuote(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    tag = db.Column(db.String(64), unique=True)
    quote = db.Column(db.String(512))
    sound_file = db.Column(db.String(128))
    order = db.Column(db.Integer)

    @classmethod
    def create_from_file(cls, file, quote, commit=True):
        from tubes import app

        # We copy the file
        _, filename = os.path.split(file)
        path = os.path.join("tubes", app.config["SOUND_FILES_FOLDER"], filename)
        copyfile(file, path)

        # We create the object in db
        name, _ = os.path.splitext(filename)
        md5 = hashlib.md5(filename.encode("utf-8"))
        order = int(md5.hexdigest(), 16)
        order = int(str(order)[:8])
        soundquote = cls(tag=name, sound_file=path, quote=quote, order=order)

        db.session.add(soundquote)
        if commit:
            db.session.commit()

        return soundquote

    def get_path(self):
        from tubes import app

        return os.path.join(app.config["SOUND_FILES_FOLDER"], "{}.mp3".format(self.tag))

    def get_html_color(self):
        return COLORS[self.order % len(COLORS)]

    def get_absolute_url(self):
        return url_for("tubes.sound_quote", tag=self.tag)

    def get_html_quote(self):
        return "".join(
            [
                u'<div class="citation">{}</div>'.format(q)
                for q in self.quote.split("\n")
            ]
        )

tubes/__init__.py
import json
import os

import click
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    app = Flask(__name__)

    app.config.from_object("settings")

    db.init_app(app)
    Migrate(app, db)

    from .views import tubes as tubes_blueprint

    app.register_blueprint(tubes_blueprint)

    return app


app = create_app()


@app.cli.command("import_quotes")
@click.argument("folder")
def import_quotes(folder):
    """Import sound quotes from a folder using folder/quotes.json"""
    from .models import SoundQuote

    folder_path = os.path.join("tubes", app.config["SOUND_FILES_FOLDER"])
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

    folder = folder or "sound_files"
    with open(os.path.join(folder, "quotes.json")) as f:
        mapping = json.load(f)

    for tag, quote in mapping.items():
        f = os.path.join(folder, u"{}.mp3".format(tag))
        SoundQuote.create_from_file(f, quote, commit=False)

    db.session.commit()

tubes/views.py
import random

from flask import Blueprint, redirect, render_template, send_file, url_for
from sqlalchemy.orm import exc
from werkzeug.exceptions import abort

from tubes.models import SoundQuote

tubes = Blueprint("tubes", __name__)


def render_tubes_template(template_name, **kwargs):
    if "sound_quotes" not in kwargs:
        kwargs["sound_quotes"] = SoundQuote.query.order_by(SoundQuote.order).all()

    return render_template(template_name, **kwargs)


@tubes.route("/")
def home():
    return render_tubes_template("home.html")


@tubes.route("/tag/<tag>")
def sound_quote(tag):
    try:
        sound_quote = SoundQuote.query.filter(SoundQuote.tag == tag).one()
    except exc.NoResultFound:
        abort(404)

    return render_tubes_template("sound_quote.html", sound_quote=sound_quote)


@tubes.route("/sound/<tag>")
def sound_file(tag):
    try:
        sound_quote = SoundQuote.query.filter(SoundQuote.tag == tag).one()
    except exc.NoResultFound:
        abort(404)

    return send_file(sound_quote.get_path(), mimetype="audio/mpeg")


@tubes.route("/tag/random")
def random_sound_quote():
    nb_sound_quotes = SoundQuote.query.count()
    sound_quote = SoundQuote.query.all()[random.randint(0, nb_sound_quotes - 1)]
    return redirect(url_for("tubes.sound_quote", tag=sound_quote.tag))

tubes/templates/base.html
<html>

    <head>
        <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="description" content="37Tubes - Les meilleures répliques du Dîner de Cons">
        <meta name="keywords" content="37tubes,37 tubes,Dîner de Cons,citations,répliques,François Pignon,Pierre Brochant,Francis Veber,Jacques Villeret,Thierry Lhermitte,Francis Huster,Daniel Prévost">

        <meta charset="UTF-8">
        <title>37Tubes</title>

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link href='//fonts.googleapis.com/css?family=Playfair+Display:400italic' rel='stylesheet' type='text/css'>
        <link href='//fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" />
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.png') }}" type="image/x-icon">
        <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}" type="image/x-icon">

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-83770907-1', 'auto');
            ga('send', 'pageview');
        </script>


        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

        <div id="main">

            <header class="text-center">
                <p class="title">37Tubes</p>
                <p class="tagline big">Extraits du Dîner de Cons</p>
                <p class="tagline">Inspiré par <a href="//ouich.es">Ouich!es</a></p>
            </header>

            {% block top_body %}{% endblock %}

            <div id="tags">
                <div id="tags-content" class="text-center">
                    {% for sound_quote in sound_quotes %}
                        <a href="{{ sound_quote.get_absolute_url() }}" id="a-{{ sound_quote.tag }}" class="tag" style="color:{{ sound_quote.get_html_color() }}">
                            #{{ sound_quote.tag }}
                        </a>
                    {% endfor %}
                </div>
            </div>

            <footer class="text-center">
                <div class="btn-group btn-group-lg" role="toolbar">
                    {#
                    <a href="//twitter.com/ouiches" target="_blank" class="btn btn-default"><span class="fa fa-twitter"></span></a>
                    <a href="//fb.com/ouiches" target="_blank" class="btn btn-default"><span class="fa fa-facebook"></span></a>
                    #}
                    <a href="mailto:francois.pignon@37tub.es" target="_blank" class="btn btn-default"><span class="fa fa-envelope"></span></a>
                    <button type="button" class="btn btn-default" onclick="toggleInfo();"><span class="fa fa-info-circle"></span></button>
                </div>
                <div id="infos" style="display:none;">
                    J'organise une petite soirée Mercredi soir, vous êtes libre ?<br/>
                    Ce site est (fortement) inspiré du site le plus classe du monde : <a href="http://ouich.es">Ouich!es</a>
                </div>
            </footer>

        </div>

        <script type="application/javascript">
            function toggleInfo() {
                $("#infos").slideToggle();
            };
        </script>

    </body>

</html>

tubes/templates/home.html
{% extends 'base.html' %}


{% block top_body %}

<div id="player">
    <div id="player-content">
        <a href="{{ url_for('tubes.random_sound_quote') }}">
            <div id="random" class="fa fa-random"></div>
        </a>
    </div>
</div>

{% endblock %}

tubes/templates/sound_quote.html
{% extends 'base.html' %}


{% block top_body %}

<div id="player">
    <div id="player-content">
        <div id="bubble" class="bubble text-center" style="background-color:{{ sound_quote.get_html_color() }}">
            <audio autoplay="" preload="true" onplay="showPlaying();" onpause="showStopped();" onended="showStopped();">;
                <source src="{{ url_for('tubes.sound_file', tag=sound_quote.tag) }}" type="audio/mp3"> Your browser does not support audio
            </audio>

            <a href="/">
                <div id="{{ sound_quote.tag }}" class="close">
                    <span class="fa fa-times"></span>
                </div>
            </a>

            <div id="bubble-main" class="replique-content">
                <div id="title">
                    <div id="btnAudio" onclick="toggle();">
                        <div id="btnIconStop" class="btnIcon fa fa-stop-circle" style="display: none;"></div>
                        <div style="display: inline-block;" id="btnIconPlay" class="btnIcon fa fa-play-circle"></div>
                    </div>

                    <span id="tag" class="replique-tag">#{{ sound_quote.tag }}</span>
                </div>

                <div clas="quotes" id="q-{{ sound_quote.tag }}">
                    {{ sound_quote.get_html_quote()|safe }}
                </div>

                {#
                <div role="toolbar" id="bubble-toolbar" class="btn-group btn-group-lg">
                    <a href="https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Fouich.es&amp;url=https%3A%2F%2Fouich.es/tag%2Fbienvenue&amp;hashtags=ouiches&amp;related=ouiches" target="_blank" class="">
                        <span class="fa fa-twitter"></span>
                    </a>
                    <a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fouich.es/tag%2Fbienvenue" target="_blank" class="">
                        <span class="fa fa-facebook"></span>
                    </a>
                    <a href="/tag/bienvenue" class="" title="Clique droit puis Copier le lien">
                        <span class="fa fa-link"></span>
                    </a>
                </div>
                #}

            </div>
        </div>

        <script type="application/javascript">
            $(
                function () {
                    var audio = $('audio')[0]
                        , btnIconPlay = $('#btnIconPlay')
                        , btnIconStop = $('#btnIconStop');

                    document.play = function () {
                        audio.play();
                    }

                    document.stop = function () {
                        audio.pause();
                    }

                    document.toggle = function () {
                        if (audio.paused) {
                            document.play();
                        } else {
                            document.stop();
                        }
                    }

                    document.showStopped = function () {
                        btnIconPlay.show();
                        btnIconStop.hide();
                    }

                    document.showPlaying = function () {
                        btnIconPlay.hide();
                        btnIconStop.show();
                    }
                }

            )
        </script>

    </div>

</div>

{% endblock %}